version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"

  redis-email-service:
    build: ./redis-service
    container_name: email-worker
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
