version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"

  mail-subscriber:
    build: .
    container_name: mail-subscriber
    depends_on:
      - redis
    environment:
      - GMAIL_HOST=smtp.gmail.com
      - GMAIL_PORT=587
      - GMAIL_SECURE=false
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASSWORD=${GMAIL_PASSWORD}
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    command: ["node", "mailSubscriber.js"]
